packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/samples/*'
  - 'apps/custom/*'
  - 'services/*'
  - 'services/custom/*'
  - 'services/samples/*'

# Default catalog
catalog:
  typescript: ^5.8.3
  tsup: ^8.4.0
  '@types/node': ^22.15.17
  eslint: ^9.26.0
  turbo: ^2.5.3
  prettier: ^3.5.3
  prettier-plugin-svelte: ^3.4.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-svelte: ^3.9.2
  '@typescript-eslint/eslint-plugin': ^8.32.0
  '@typescript-eslint/parser': ^8.32.0
  dotenv: ^16.5.0
  '@aws-sdk/client-bedrock-runtime': ^3.810.0
  '@aws-sdk/client-dynamodb': ^3.810.0
  '@aws-sdk/util-dynamodb': ^3.810.0
  '@aws-sdk/client-lambda': ^3.810.0
  '@aws-sdk/client-ssm': ^3.810.0
  '@aws-sdk/lib-dynamodb': ^3.810.0
  '@aws-sdk/client-bedrock-agent-runtime': ^3.810.0
  '@aws-sdk/client-s3': ^3.810.0
  '@aws-sdk/s3-request-presigner': ^3.810.0
  '@aws-sdk/client-sts': ^3.810.0
  '@aws-sdk/credential-provider-node': ^3.810.0
  '@smithy/signature-v4': ^5.1.2
  '@aws-crypto/sha256-js': ^5.2.0
  '@smithy/node-http-handler': ^4.0.3
  camelcase-keys: ^9.1.3
  snakecase-keys: ^8.0.1
  uuid: ^11.1.0
  aws-cdk: ^2.1018.0
  aws-cdk-lib: ^2.195.0
  constructs: ^10.4.2
  source-map-support: ^0.5.21
  ts-node: ^10.9.2
  tslib: ^2.8.1
  aws-lambda: ^1.0.7
  '@types/aws-lambda': ^8.10.149
  lambda-stream: ^0.6.0
  '@iconify-json/ci': ^1.2.2
  '@iconify-json/lucide': ^1.2.44
  '@internationalized/date': ^3.8.0
  '@sveltejs/adapter-auto': ^6.0.1
  '@sveltejs/adapter-node': ^5.2.12
  '@sveltejs/kit': ^2.21.0
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  svelte-sonner: ^1.0.1
  vite: ^6.3.5
  svelte: ^5.30.2
  svelte-check: ^4.2.1
  '@tailwindcss/typography': ^0.5.16
  '@tanstack/table-core': ^8.21.3
  autoprefixer: ^10.4.21
  bits-ui: ^1.4.8
  date-fns: ^4.1.0
  dompurify: ^3.2.5
  marked: ^15.0.11
  markdown-it: ^14.1.0
  '@types/markdown-it': ^14.1.2
  tsx: ^4.19.4
  unplugin-icons: ^22.1.0
  tailwind-merge: ^3.0.2
  tailwind-variants: ^1.0.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  cssnano: ^7.0.7
  postcss: ^8.5.4
  clsx: ^2.1.1
  papaparse: ^5.5.2
  '@types/papaparse': ^5.3.16
  glob: ^11.0.2
  mode-watcher: ^1.0.7
  path: ^0.12.7
  esbuild: ^0.25.4
  jsonwebtoken: ^9.0.2
  '@types/jsonwebtoken': ^9.0.9
  'chart.js': ^4.4.9
  duckdb: ^1.2.1
  jest: ^29.7.0
  'ts-jest': ^29.3.2
  '@types/jest': ^29.5.14
  'p-retry': ^6.2.1
  'lodash.clonedeep': ^4.5.0
  '@types/lodash.clonedeep': ^4.5.9
  'lodash.findindex': ^4.6.0
  '@types/lodash.findindex': ^4.6.9
  'lodash.isequalwith': ^4.4.0
  '@types/lodash.isequalwith': ^4.4.9
  'lru-cache': ^11.1.0
  plur: ^5.1.0
  indefinite: ^2.5.1
  '@types/indefinite': ^2.3.4
  '@auth/sveltekit': ^1.9.2
  '@auth/core': ^0.39.1
  commander: ^14.0.0
  inquirer: ^12.6.3
  '@types/inquirer': ^9.0.8
  chalk: ^5.4.1
  ora: ^8.2.0
  fs-extra: ^11.3.0
  '@types/fs-extra': ^11.0.4
  semver: ^7.7.2
  '@types/semver': ^7.7.0
  mustache: ^4.2.0
  '@types/mustache': ^4.2.6
  yaml: ^2.8.0
  minimatch: ^10.0.3
  diff: ^8.0.2