#!/usr/bin/env node

/**
 * This script generates TypeScript declaration files for available icons from installed Iconify packages
 * to provide IDE autocomplete while maintaining perfect tree-shaking.
 *
 * Modified for pika-ux: generates types in src/icons/ and exports them for consumers
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Path to the icons directory (in src/icons for pika-ux)
const iconsDirPath = path.resolve(__dirname, '../../src/icons');

// Ensure the icons directory exists
if (!existsSync(iconsDirPath)) {
    mkdirSync(iconsDirPath, { recursive: true });
}

// Function to get all icon names from a collection
function getIconNamesFromCollection(collectionName: string): string[] {
    try {
        const collectionPath = path.resolve(__dirname, `../../node_modules/@iconify-json/${collectionName}/icons.json`);

        if (!existsSync(collectionPath)) {
            console.log(`Collection ${collectionName} not found at ${collectionPath}`);
            return [];
        }

        const collectionData = JSON.parse(readFileSync(collectionPath, 'utf8'));
        // The icons are in the "icons" object of the JSON
        return Object.keys(collectionData.icons || {});
    } catch (error) {
        console.error(`Error reading collection ${collectionName}:`, error);
        return [];
    }
}

// Get all installed Iconify collections
function getInstalledCollections(): string[] {
    const nodeModulesPath = path.resolve(__dirname, '../../node_modules/@iconify-json');

    if (!existsSync(nodeModulesPath)) {
        console.log('No @iconify-json packages found');
        return [];
    }

    // Filter out hidden files and directories
    return readdirSync(nodeModulesPath).filter((item) => !item.startsWith('.'));
}

// Generate TypeScript declaration content for all icons in a collection
function generateCollectionDeclarationContent(collection: string, iconNames: string[]): string {
    const declarations = iconNames.map(
        (iconName) =>
            `declare module '$icons/${collection}/${iconName}' {
  import type { Component } from 'svelte';
  import type { SvelteHTMLElements } from 'svelte/elements';
  const component: Component<SvelteHTMLElements['svg']>;
  export default component;
}`
    );

    return `// ${collection} icons - Type declarations only
// Auto-generated by tools/icon-generator/generate-icon-ts-indices.ts
// These declarations provide IDE autocomplete without runtime imports
// Exported by pika-ux for consumer projects

${declarations.join('\n\n')}
`;
}

// Main function
function main(): void {
    const collections = getInstalledCollections();

    if (collections.length === 0) {
        console.log('No Iconify collections found. Please install some with:');
        console.log('pnpm install @iconify-json/lucide @iconify-json/ci');
        return;
    }

    console.log(`Found ${collections.length} Iconify collections: ${collections.join(', ')}`);

    const collectionsWithIcons: string[] = [];

    collections.forEach((collection) => {
        const iconNames = getIconNamesFromCollection(collection);
        console.log(`Found ${iconNames.length} icons in ${collection}`);

        if (iconNames.length > 0) {
            collectionsWithIcons.push(collection);

            // Create the collection directory
            const collectionDirPath = path.resolve(iconsDirPath, collection);
            if (!existsSync(collectionDirPath)) {
                mkdirSync(collectionDirPath, { recursive: true });
            }

            // Generate a declaration file for the collection
            const collectionFilePath = path.resolve(collectionDirPath, 'index.d.ts');
            const content = generateCollectionDeclarationContent(collection, iconNames);
            writeFileSync(collectionFilePath, content);
            console.log(`Created ${collectionFilePath}`);
        }
    });

    console.log(`Icon declaration files generation complete! Generated types for ${collectionsWithIcons.length} collections.`);
    console.log('These types will be exported by pika-ux and consumed by other projects.');
}

main();
