#!/usr/bin/env node

/**
 * This script generates TypeScript declaration files for available icons from installed Iconify packages
 * to provide IDE autocomplete while maintaining perfect tree-shaking.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Path to the icons directory
const iconsDirPath = path.resolve(__dirname, '../../src/lib/icons');

// Ensure the icons directory exists
if (!existsSync(iconsDirPath)) {
    mkdirSync(iconsDirPath, { recursive: true });
}

// Function to get all icon names from a collection
function getIconNamesFromCollection(collectionName: string): string[] {
    try {
        const collectionPath = path.resolve(__dirname, `../../node_modules/@iconify-json/${collectionName}/icons.json`);

        if (!existsSync(collectionPath)) {
            console.log(`Collection ${collectionName} not found at ${collectionPath}`);
            return [];
        }

        const collectionData = JSON.parse(readFileSync(collectionPath, 'utf8'));
        // The icons are in the "icons" object of the JSON
        return Object.keys(collectionData.icons || {});
    } catch (error) {
        console.error(`Error reading collection ${collectionName}:`, error);
        return [];
    }
}

// Get all installed Iconify collections
function getInstalledCollections(): string[] {
    const nodeModulesPath = path.resolve(__dirname, '../../node_modules/@iconify-json');

    if (!existsSync(nodeModulesPath)) {
        console.log('No @iconify-json packages found');
        return [];
    }

    // Filter out hidden files and directories
    return readdirSync(nodeModulesPath).filter((item) => !item.startsWith('.'));
}

// Generate TypeScript declaration content for all icons in a collection
function generateCollectionDeclarationContent(collection: string, iconNames: string[]): string {
    const declarations = iconNames.map(
        (iconName) =>
            `declare module '$icons/${collection}/${iconName}' {
  const component: any;
  export default component;
}`
    );

    return `// ${collection} icons - Type declarations only
// Auto-generated by tools/generate-icon-ts-indices.ts
// These declarations provide IDE autocomplete without runtime imports

${declarations.join('\n\n')}
`;
}

// Update app.d.ts with triple-slash references
function updateAppDtsReferences(collections: string[]): void {
    const appDtsPath = path.resolve(__dirname, '../../src/app.d.ts');

    if (!existsSync(appDtsPath)) {
        console.log('app.d.ts not found, skipping reference updates');
        return;
    }

    let content = readFileSync(appDtsPath, 'utf8');

    // 1. Parse all existing triple-slash references
    const existingReferences = new Set<string>();
    const tripleSlashRegex = /\/\/\/\s*<reference path="([^"]+)"\s*\/>/g;
    let match;
    while ((match = tripleSlashRegex.exec(content)) !== null) {
        existingReferences.add(match[1]);
    }

    // 2. Compare with what we want to add for each icon collection
    const desiredReferences = collections.map((collection) => `./lib/icons/${collection}/index.d.ts`);
    const missingReferences = desiredReferences.filter((ref) => !existingReferences.has(ref));

    // 3. Only add missing references
    if (missingReferences.length > 0) {
        const newReferences = missingReferences.map((ref) => `/// <reference path="${ref}" />`);

        // Find the best insertion point
        let insertionIndex = -1;

        // First, try to find existing icon references and add after the last one
        const iconReferenceRegex = /\/\/\/\s*<reference path="\.\/lib\/icons\/[^"]+\/index\.d\.ts"\s*\/>/g;
        let lastIconMatch;
        while ((lastIconMatch = iconReferenceRegex.exec(content)) !== null) {
            insertionIndex = lastIconMatch.index + lastIconMatch[0].length;
        }

        // If no existing icon references, look for the comment
        if (insertionIndex === -1) {
            const commentMatch = content.match(/\/\/\s*Include our custom icon declaration files/);
            if (commentMatch) {
                const commentEnd = commentMatch.index! + commentMatch[0].length;
                const nextLineIndex = content.indexOf('\n', commentEnd) + 1;
                insertionIndex = nextLineIndex;
            }
        }

        // If still no good spot, insert after unplugin-icons import
        if (insertionIndex === -1) {
            const unpluginsImport = content.indexOf("import 'unplugin-icons/types/svelte';");
            if (unpluginsImport !== -1) {
                const lineEnd = content.indexOf('\n', unpluginsImport) + 1;
                insertionIndex = lineEnd;
                newReferences.unshift('', '// Include our custom icon declaration files');
            }
        }

        if (insertionIndex !== -1) {
            const before = content.slice(0, insertionIndex);
            const after = content.slice(insertionIndex);
            const referencesToAdd = newReferences.join('\n');

            content = `${before}\n${referencesToAdd}${after}`;

            writeFileSync(appDtsPath, content);
            console.log(
                `Added ${missingReferences.length} missing icon references to app.d.ts: ${missingReferences.map((ref) => ref.split('/').pop()?.replace('index.d.ts', '')).join(', ')}`
            );
        } else {
            console.log('Could not find insertion point in app.d.ts');
        }
    } else {
        console.log('All icon references already exist in app.d.ts');
    }
}

// Main function
function main(): void {
    const collections = getInstalledCollections();

    if (collections.length === 0) {
        console.log('No Iconify collections found. Please install some with:');
        console.log('npm install -D @iconify-json/lucide @iconify-json/fa @iconify-json/mdi');
        return;
    }

    console.log(`Found ${collections.length} Iconify collections: ${collections.join(', ')}`);

    const collectionsWithIcons: string[] = [];

    collections.forEach((collection) => {
        const iconNames = getIconNamesFromCollection(collection);
        console.log(`Found ${iconNames.length} icons in ${collection}`);

        if (iconNames.length > 0) {
            collectionsWithIcons.push(collection);

            // Create the collection directory
            const collectionDirPath = path.resolve(iconsDirPath, collection);
            if (!existsSync(collectionDirPath)) {
                mkdirSync(collectionDirPath, { recursive: true });
            }

            // Generate a declaration file for the collection
            const collectionFilePath = path.resolve(collectionDirPath, 'index.d.ts');
            const content = generateCollectionDeclarationContent(collection, iconNames);
            writeFileSync(collectionFilePath, content);
            console.log(`Created ${collectionFilePath}`);
        }
    });

    // Update app.d.ts with references to the generated files
    updateAppDtsReferences(collectionsWithIcons);

    console.log('Icon declaration files generation complete!');
}

main();
