export const weatherSuggestions = [
    'What is the weather in Tokyo?',
    'Compare the weather in Tokyo and San Francisco in the last 30 days',
    'What will the temperature be in Paris tomorrow?',
    'Will it rain in London this weekend?',
    'What is the current weather in New York City?',
    'Show me the forecast for Sydney for the next week',
    'What is the air quality index in Beijing today?',
    'How hot will it be in Dubai next Tuesday?',
    'Is there a storm coming to Miami?',
    'What\'s the humidity level in Singapore right now?',
    'When will the sun set in Oslo today?',
    'What\'s the UV index in Cancun this week?',
    'Will it snow in Toronto tomorrow?',
    'What\'s the wind speed in Chicago right now?',
    'How cold will it get in Moscow tonight?',
    'What\'s the weather forecast for Berlin this weekend?',
    'Is it foggy in San Francisco today?',
    'What\'s the chance of rain in Seoul tomorrow?',
    'How does the weather in Auckland compare to Wellington?',
    'What\'s the temperature history for Cairo over the past month?',
    'When will it start raining in Mumbai?',
    'What\'s the marine forecast for the Mediterranean Sea?',
    'Is there a heat wave coming to Phoenix?',
    'What\'s the precipitation forecast for Seattle this week?',
    'How humid will it be in Bangkok next week?',
    'What\'s the weather like in Cape Town right now?',
    'Will there be clouds in Amsterdam tomorrow?',
    'What\'s the air pressure in Denver today?',
    'How hot was it in Rome yesterday?',
    'What\'s the climate forecast for Vancouver next month?',
    'Is Boston colder than New York this winter?',
    'What\'s the marine weather in the Gulf of Mexico?',
    'When will the temperature drop below freezing in Montreal?',
    'What\'s the air quality like in Los Angeles today?',
    'How windy is it in Wellington right now?',
    'What\'s the historical average temperature for Barcelona in July?',
    'Will it be sunny in Honolulu this weekend?',
    'What\'s the visibility in Istanbul right now?',
    'How does this summer compare to last summer in Melbourne?',
    'What\'s the dewpoint in Houston today?',
    'Will there be thunderstorms in Miami this week?',
    'What\'s the snow forecast for Aspen next week?',
    'How much rain will fall in Rio de Janeiro this month?',
    'What\'s the temperature range in Las Vegas today?',
    'Is the air quality good in Delhi right now?',
    'What\'s the UV forecast for Nairobi this weekend?',
    'Will there be fog in San Diego tomorrow morning?',
    'What\'s the humidity forecast for Kuala Lumpur?',
    'How hot was the hottest day in Athens last year?',
    'What\'s the marine forecast for the Baltic Sea?',
    'Is there a cold front moving into Atlanta?',
    'What\'s the cloud cover in Stockholm today?',
    'How much snow has fallen in Zurich this winter?',
    'What\'s the weather like in Marrakech right now?',
    'Will I need an umbrella in Taipei tomorrow?',
    'What\'s the air quality forecast for Mexico City this week?',
    'How does the current temperature in Rome compare to the historical average?',
    'What\'s the heat index in New Orleans today?',
    'Is there a frost warning for Portland tonight?',
    'What\'s the marine weather around the Hawaiian islands?',
    'How many rainy days has London had this month?',
    'What\'s the climate outlook for Berlin in 2023?',
    'Will there be a drought in California this summer?',
    'What\'s the pollen count in Atlanta today?',
    'How cold is it in Reykjavik compared to Oslo?',
    'What\'s the weather pattern in the Sahara this week?',
    'Is there a tropical storm forming in the Atlantic?',
    'What\'s the windchill in Quebec City today?',
    'How much hotter is it in Phoenix than in San Diego?',
    'What\'s the air quality index trend in Shanghai this month?',
    'Will it be safe to sail in the Mediterranean this weekend?',
    'What\'s the chance of flooding in Bangkok this monsoon season?',
    'How has the temperature in Paris changed in the last decade?',
    'What\'s the current visibility at JFK airport?',
    'Is there a tornado warning in Oklahoma City?',
    'What\'s the wave height off the coast of Hawaii today?',
    'How hot was the hottest day ever recorded in Baghdad?',
    'What\'s the weather like for hiking in the Swiss Alps this weekend?',
    'Will it be good beach weather in Bali next week?',
    'What\'s the seasonal weather pattern in Mumbai?',
    'How much has sea level risen in Venice in the past 50 years?',
    'What\'s the record high temperature for Dubai in August?',
    'Is there a blizzard forecast for Denver this winter?',
    'What\'s the air quality like after wildfires in California?',
    'How does El Niño affect the weather in Santiago?',
    'What\'s the current sea temperature in the Maldives?',
    'Will there be northern lights visible in Iceland this week?',
    'What\'s the temperature difference between day and night in the Sahara?',
    'How has climate change affected rainfall in Kenya?',
    'What\'s the weather like for skiing in the Alps next month?',
    'Is there a hurricane approaching the Caribbean?',
    'What\'s the historical weather pattern for Rio during Carnival?',
    'How much rainfall has Amazon rainforest received this year?',
    'What\'s the current temperature at Mount Everest base camp?',
    'Will there be clear skies for stargazing in Arizona tonight?',
    'What\'s the fire danger level in Australia this summer?',
    'How will climate change affect Singapore by 2050?',
    'What\'s the typical weather in Santorini in May?'
];