import * as cdk from 'aws-cdk-lib';
import { Certificate, ICertificate } from 'aws-cdk-lib/aws-certificatemanager';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecr_assets from 'aws-cdk-lib/aws-ecr-assets';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecs_patterns from 'aws-cdk-lib/aws-ecs-patterns';
import { ApplicationProtocol, SslPolicy } from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as nodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import { LogGroup, RetentionDays } from 'aws-cdk-lib/aws-logs';
import { HostedZone } from 'aws-cdk-lib/aws-route53';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import { Construct } from 'constructs';
import { readFileSync } from 'fs';
import * as path from 'path';
import { TagDefinitionsJsonFile } from 'pika-shared/types/chatbot/chatbot-types.js';
import { fileURLToPath } from 'url';
import { gzipSync } from 'zlib';
import { generateKmsKeyAliasName } from '../../../src/lib/server/encryption/kms-utils';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const COOKIE_MAX_AGE_HOURS = 12;
const KEY_ROTATION_INTERVAL_HOURS = 12;
const KEY_REFRESH_INTERVAL_HOURS = 1;
const MAX_KEY_VERSIONS = '3';

export interface PikaChatConstructProps {
    /**
     * The stage/environment name (e.g., 'dev', 'staging', 'prod')
     */
    stage: string;

    /**
     * VPC to deploy the service into
     */
    vpc: ec2.IVpc;

    /**
     * Certificate ARN for HTTPS, if provided will use Certificate.fromCertificateArn to create the certificate.
     * Use this or certificate, not both. You must provide one or the other.
     */
    certificateArn?: string;

    /**
     * Certificate for HTTPS, if provided will use as is in ecs task definition.
     * Use this or certificateArn, not both. You must provide one or the other.
     */
    certificate?: ICertificate;

    /**
     * Domain name for the pika chat webapp (e.g., 'chat.example.com' or 'test-chat.example.com'). Must be fully qualified domain name.
     */
    domainName?: string;

    /**
     * Hosted Zone ID for Route53 (optional).  If provided, domainName must also be provided and the domain must be in this hosted zone.
     */
    hostedZoneId?: string;

    /**
     * Path to the directory containing the Dockerfile (relative to this construct file)
     */
    dockerBuildPath: string;

    /**
     * Additional environment variables to add to the ECS task
     */
    additionalEnvironmentVariables?: Record<string, string>;

    /**
     * Whether to make the load balancer public (default: false)
     */
    makeLoadBalancerPublic?: boolean;

    /**
     * CPU units for the Fargate task (default: 512)
     */
    cpu?: number;

    /**
     * Memory limit in MiB for the Fargate task (default: 2048)
     */
    memoryLimitMiB?: number;

    /**
     * Desired count of running tasks (default: 1)
     */
    desiredCount?: number;

    /**
     * Container port (default: 3000)
     */
    containerPort?: number;

    /**
     * Health check path (default: '/health')
     */
    healthCheckPath?: string;

    /**
     * Log retention period (default: ONE_WEEK)
     */
    logRetention?: RetentionDays;

    /**
     * Project name in all lowercase e.g. pikachat
     */
    projNameL: string;

    /**
     * Project name in title case e.g. PikaChat
     */
    projNameTitleCase: string;

    /**
     * Project name in camel case e.g. pikaChat
     */
    projNameCamel: string;

    /**
     * Project name in kebab case e.g. pika-chat
     */
    projNameKebabCase: string;

    /**
     * Project name in human readable e.g. Pika Chat
     */
    projNameHuman: string;

    /**
     * Project name in kebab case for the pika service stack e.g. pika
     */
    pikaServiceProjNameKebabCase: string;

    /**
     * Tag definitions for the pika chat stack.  This is generated by the generate-tag-defs-for-build tool.
     */
    tagDefinitions: TagDefinitionsJsonFile;

    /**
     * Stack tags to apply to resources (merged common + chat-specific tags from pika-config.ts).
     * These are the interpolated tags that are passed as environment variables for cost tracking.
     */
    stackTags?: Record<string, string>;

    /**
     * Component tag names to apply to all infrastructure.
     * If provided, each infrastructure resource will be tagged with these key names and a component-specific value.
     */
    componentTagNames?: string[];

    /**
     * If true, route the chat app to the Strands (Python) converse Lambda by reading the
     * `converse_strands_url` SSM parameter instead of `converse_url`. Must match the value
     * passed to the pika service stack (`pikaConfig.siteFeatures.strandsConverse.enabled`),
     * which determines whether `ConverseStrandsConstruct` is deployed and publishes the
     * `converse_strands_url` parameter. Default: false (use the TypeScript converse Lambda).
     * @since 0.25.1
     */
    useStrandsConverse?: boolean;
}

/** Includes the things we know have to be provided by whomever implements the getPikaChatConstructProps function. */
export type PartialPikaChatConstructProps = Omit<PikaChatConstructProps, 'vpc'>;

export class PikaChatConstruct extends Construct {
    public readonly service: ecs_patterns.ApplicationLoadBalancedFargateService;
    public readonly cluster: ecs.Cluster;
    public readonly dockerImage: ecr_assets.DockerImageAsset;
    public readonly taskRole: iam.Role;
    private readonly props: PikaChatConstructProps;

    constructor(scope: Construct, id: string, props: PikaChatConstructProps) {
        super(scope, id);
        this.props = props;

        //BXTODO
        // Build the full domain name

        // Create Docker image asset
        this.dockerImage = new ecr_assets.DockerImageAsset(this, `${props.projNameTitleCase}Image`, {
            directory: props.dockerBuildPath,
            buildArgs: {
                BUILDPLATFORM: 'linux/amd64'
            },
            platform: ecr_assets.Platform.LINUX_AMD64
        });
        this.applyComponentTags(this.dockerImage, 'DockerImageAsset');

        // Store the image URI in SSM for reference by other services
        new ssm.StringParameter(this, `${props.projNameTitleCase}EcrImageUriParam`, {
            parameterName: `/stack/${props.projNameKebabCase}/${props.stage}/ecr/${props.projNameKebabCase}-image-uri`,
            stringValue: this.dockerImage.imageUri,
            description: `URI of the ${props.projNameHuman} Docker image in ECR`
        });

        // Create ECS cluster
        this.cluster = new ecs.Cluster(this, `${props.projNameTitleCase}Cluster`, {
            vpc: props.vpc
        });
        this.applyComponentTags(this.cluster, 'ECSCluster');

        // Param comes from the pika service stack
        const apiId = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/api/id`);

        // Param comes from the pika service stack
        const chatAdminApiId = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/api/chat_admin_id`);

        // Param comes from the pika service stack. SSM key is flag-conditional: when
        // `useStrandsConverse` is true (matching `pikaConfig.siteFeatures.strandsConverse.enabled`),
        // read the Strands (Python) Lambda URL; otherwise read the TypeScript Lambda URL.
        const converseUrlParamKey = props.useStrandsConverse ? 'converse_strands_url' : 'converse_url';
        const converseFnUrl = ssm.StringParameter.valueForStringParameter(
            this,
            `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/function/${converseUrlParamKey}`
        );

        // Param comes from the pika service stack
        const chatAppTableArn = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/ddb_table/chat_app_table_arn`);

        // Param comes from the pika service stack
        const pikaS3Bucket = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/s3/pika_bucket_name`);

        // Param comes from the pika service stack
        const pikaS3BucketArn = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/s3/pika_bucket_arn`);

        // Param comes from the pika service stack
        const tagDefinitionsTableArn = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/ddb_table/pika_tag_def_arn`);

        // Param comes from the pika service stack
        const tagDefinitionsTableName = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/ddb_table/pika_tag_def`);

        // ===== COOKIE ENCRYPTION INFRASTRUCTURE =====

        // IAM role for key rotation Lambda
        const rotationFunctionRole = new iam.Role(this, `${props.projNameTitleCase}KeyRotationRole`, {
            assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
            managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
            inlinePolicies: {
                KeyRotationPolicy: new iam.PolicyDocument({
                    statements: [
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['ssm:GetParameter', 'ssm:GetParameters', 'ssm:GetParametersByPath', 'ssm:PutParameter', 'ssm:DeleteParameter'],
                            resources: [
                                `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption`,
                                `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption/*`
                            ]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:GenerateDataKey', 'kms:Decrypt'],
                            resources: ['*'],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/Project': props.projNameKebabCase,
                                    'aws:ResourceTag/Stage': props.stage,
                                    'aws:ResourceTag/Purpose': 'CookieEncryption'
                                }
                            }
                        })
                    ]
                })
            }
        });

        // Lambda function for key rotation (scheduled and invoked by initializer)
        const rotationFunction = new nodejs.NodejsFunction(this, `${props.projNameTitleCase}KeyRotationFunction`, {
            functionName: `${props.projNameTitleCase}KeyRotationFunction-${props.stage}`,
            runtime: lambda.Runtime.NODEJS_22_X,
            entry: 'infra/lambda/cookie-key-rotation/index.ts',
            handler: 'handler',
            timeout: cdk.Duration.seconds(60),
            memorySize: 256,
            environment: {
                NODE_OPTIONS: '--enable-source-maps',
                STAGE: props.stage,
                SSM_PARAMETER_PREFIX: `/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption`,
                KMS_KEY_ALIAS: generateKmsKeyAliasName(props.projNameKebabCase, props.stage),
                MAX_KEY_VERSIONS: MAX_KEY_VERSIONS
            },
            role: rotationFunctionRole,
            bundling: {
                minify: true,
                sourceMap: true,
                target: 'node22',
                externalModules: ['@aws-sdk']
            }
        });
        this.applyComponentTags(rotationFunction, 'CookieKeyRotationLambda');

        // IAM role for KMS key initializer Lambda (Custom Resource)
        // This Lambda only creates KMS keys and SSM key alias parameters
        const keyInitializerFunctionRole = new iam.Role(this, `${props.projNameTitleCase}KeyInitializerRole`, {
            assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
            managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
            inlinePolicies: {
                KeyInitializerPolicy: new iam.PolicyDocument({
                    statements: [
                        // SSM permissions for storing key alias
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['ssm:PutParameter', 'ssm:DeleteParameter', 'ssm:GetParameter', 'ssm:GetParametersByPath'],
                            resources: [`arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/kms/*`]
                        }),
                        // SSM permissions for cookie encryption parameters (needed for rotateKeys call)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['ssm:GetParameter', 'ssm:GetParameters', 'ssm:GetParametersByPath', 'ssm:PutParameter', 'ssm:DeleteParameter'],
                            resources: [
                                // Parent path permission (required for GetParametersByPath)
                                `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption`,
                                // Child parameters permission
                                `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption/*`
                            ]
                        }),
                        // KMS CreateKey with key specification conditions
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:CreateKey'],
                            resources: ['*'],
                            conditions: {
                                StringEquals: {
                                    'kms:KeySpec': 'SYMMETRIC_DEFAULT',
                                    'kms:KeyUsage': 'ENCRYPT_DECRYPT'
                                }
                            }
                        }),
                        // KMS permissions for initial key setup (before tag-based conditions can apply)
                        // This is needed because we perform various KMS operations during key creation,
                        // before keys have any tags that the tag-based conditions can match
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: [
                                'kms:TagResource',
                                'kms:CreateAlias',
                                'kms:GenerateDataKey',
                                'kms:Decrypt',
                                'kms:DescribeKey'
                            ],
                            resources: [`arn:aws:kms:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:key/*`]
                        }),
                        // KMS key policy management (unrestricted for key creation)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:PutKeyPolicy', 'kms:GetKeyPolicy'],
                            resources: [`arn:aws:kms:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:key/*`]
                        }),
                        // KMS alias operations (unrestricted for key infrastructure setup)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:CreateAlias', 'kms:DeleteAlias'],
                            resources: [`arn:aws:kms:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:alias/*`]
                        }),

                        // KMS key operations - restricted to keys with specific tags
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: [
                                'kms:DescribeKey',
                                'kms:ScheduleKeyDeletion',
                                'kms:CancelKeyDeletion', // In case deletion needs to be cancelled
                                'kms:EnableKey', // In case key gets disabled
                                'kms:TagResource',
                                'kms:CreateAlias', // Needed on key resource when creating alias
                                'kms:DeleteAlias' // Needed on key resource when deleting alias
                            ],
                            resources: [`arn:aws:kms:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:key/*`],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/Project': props.projNameKebabCase,
                                    'aws:ResourceTag/Stage': props.stage,
                                    'aws:ResourceTag/Purpose': 'CookieEncryption'
                                }
                            }
                        }),

                        // KMS ListAliases (requires * and no conditions work reliably)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:ListAliases'],
                            resources: ['*']
                        }),
                        // KMS data key operations for key rotation (needed for rotateKeys call)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:GenerateDataKey', 'kms:Decrypt'],
                            resources: ['*'],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/Project': props.projNameKebabCase,
                                    'aws:ResourceTag/Stage': props.stage,
                                    'aws:ResourceTag/Purpose': 'CookieEncryption'
                                }
                            }
                        }),
                        // STS permissions for getting account ID
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['sts:GetCallerIdentity'],
                            resources: ['*']
                        })
                    ]
                })
            }
        });

        // Lambda function for KMS key initialization (Custom Resource)
        // This only creates KMS keys, not the encryption key rotation
        const keyInitializerFunction = new nodejs.NodejsFunction(this, `${props.projNameTitleCase}KeyInitializerFunction`, {
            runtime: lambda.Runtime.NODEJS_22_X,
            entry: 'infra/lambda/cookie-key-initializer/index.ts',
            handler: 'handler',
            timeout: cdk.Duration.seconds(300), // Increased timeout for KMS operations
            memorySize: 512, // Increased memory for AWS SDK operations
            environment: {
                NODE_OPTIONS: '--enable-source-maps',
                STAGE: props.stage,
                SSM_PARAMETER_PREFIX: `/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption`,
                KMS_KEY_ALIAS: generateKmsKeyAliasName(props.projNameKebabCase, props.stage),
                MAX_KEY_VERSIONS: MAX_KEY_VERSIONS,
                ...this.getTagEnvironmentVariables()
            },
            role: keyInitializerFunctionRole,
            bundling: {
                minify: true,
                sourceMap: true,
                target: 'node22',
                externalModules: ['@aws-sdk']
            }
        });
        this.applyComponentTags(keyInitializerFunction, 'CookieKeyInitializerLambda');

        // EventBridge rule for scheduled rotation (every 12 hours)
        new events.Rule(this, `${props.projNameTitleCase}KeyRotationRule`, {
            schedule: events.Schedule.rate(cdk.Duration.hours(KEY_ROTATION_INTERVAL_HOURS)),
            targets: [
                new targets.LambdaFunction(rotationFunction, {
                    event: events.RuleTargetInput.fromObject({
                        // Using environment variables for scheduled invocations
                        // forceRotation is not set, so it will check if rotation is needed
                    })
                })
            ]
        });

        // Custom resource for KMS key initialization
        // This will create KMS keys and invoke rotation function for initial key setup
        const keyInitializerCustomResource = new cdk.CustomResource(this, `${props.projNameTitleCase}KeyInitializerCustomResource`, {
            serviceToken: keyInitializerFunction.functionArn,
            properties: {
                // Add timestamp to ensure custom resource runs on every deployment
                Timestamp: Date.now().toString(),
                Stage: props.stage,
                ProjectName: props.projNameKebabCase
            }
        });

        // Create task role with necessary permissions
        this.taskRole = new iam.Role(this, `${props.projNameTitleCase}TaskRole`, {
            assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
            inlinePolicies: {
                ExecuteApiPolicy: new iam.PolicyDocument({
                    statements: [
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['execute-api:Invoke'],
                            resources: [
                                `arn:aws:execute-api:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:${apiId}/*`,
                                `arn:aws:execute-api:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:${chatAdminApiId}/*`
                            ]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['execute-api:Invoke'],
                            resources: [`arn:aws:execute-api:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:*/*`],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/pika-api': 'true'
                                }
                            }
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['ssm:GetParameter', 'ssm:GetParameters', 'ssm:GetParametersByPath'],
                            resources: [`arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/*`]
                        }),
                        // KMS permissions for cookie encryption/decryption
                        // Tag-based conditions restrict access to only keys tagged for this project/stage
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:Decrypt', 'kms:GenerateDataKey'],
                            resources: [`arn:aws:kms:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:key/*`],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/Project': props.projNameKebabCase,
                                    'aws:ResourceTag/Stage': props.stage,
                                    'aws:ResourceTag/Purpose': 'CookieEncryption'
                                }
                            }
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['lambda:InvokeFunctionUrl', 'lambda:InvokeFunction'],
                            resources: [
                                ssm.StringParameter.valueForStringParameter(
                                    this,
                                    `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/function/converse_arn` // TS converse Lambda
                                ),
                                ssm.StringParameter.valueForStringParameter(
                                    this,
                                    `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/function/converse_strands_arn` // Strands converse Lambda
                                ),
                            ]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['sts:GetCallerIdentity'],
                            resources: ['*']
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['dynamodb:GetItem', 'dynamodb:Query', 'dynamodb:Scan', 'dynamodb:BatchGetItem'],
                            resources: [chatAppTableArn]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['s3:GetObject', 's3:PutObject', 's3:DeleteObject', 's3:GetObjectAcl', 's3:PutObjectAcl', 's3:PutObjectTagging'],
                            resources: [pikaS3BucketArn, `${pikaS3BucketArn}/*`]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: [
                                'dynamodb:GetItem',
                                'dynamodb:PutItem',
                                'dynamodb:UpdateItem',
                                'dynamodb:DeleteItem',
                                'dynamodb:Query',
                                'dynamodb:Scan',
                                'dynamodb:BatchGetItem',
                                'dynamodb:BatchWriteItem'
                            ],
                            resources: [tagDefinitionsTableArn, `${tagDefinitionsTableArn}/*`]
                        })
                    ]
                })
            }
        });

        // Build environment variables
        const baseEnvironmentVariables: Record<string, string> = {
            STAGE: props.stage,
            ENV: props.stage,
            AWS_REGION: cdk.Aws.REGION,
            AWS_ACCOUNT_ID: cdk.Aws.ACCOUNT_ID,
            CHAT_API_ID: apiId,
            CHAT_ADMIN_API_ID: chatAdminApiId,
            WEBAPP_URL: props.domainName
                ? cdk.Fn.sub('${Value}', {
                      Value: `https://${props.domainName}`
                  }).toString()
                : 'unknown',
            PIKA_S3_BUCKET: pikaS3Bucket,
            CONVERSE_FUNCTION_URL: converseFnUrl,
            TAG_DEFINITIONS_TABLE: tagDefinitionsTableName,
            PIKA_SERVICE_PROJ_NAME_KEBAB_CASE: props.pikaServiceProjNameKebabCase,
            PIKA_CHAT_PROJ_NAME_KEBAB_CASE: props.projNameKebabCase,
            // Cookie key rotation configuration - will be created by infrastructure manager
            KMS_COOKIE_KEY_ALIAS: generateKmsKeyAliasName(props.projNameKebabCase, props.stage),
            KEY_REFRESH_INTERVAL_HOURS: String(KEY_REFRESH_INTERVAL_HOURS),
            MAX_KEY_VERSIONS: String(MAX_KEY_VERSIONS),
            COOKIE_MAX_AGE_HOURS: String(COOKIE_MAX_AGE_HOURS)
        };

        // Add tag environment variables if configured
        const tagEnvVars = this.getTagEnvironmentVariables();
        Object.assign(baseEnvironmentVariables, tagEnvVars);

        const environmentVariables = {
            ...baseEnvironmentVariables,
            ...props.additionalEnvironmentVariables
        };

        // Create log group first to preserve logical ID
        const logGroup = new LogGroup(this, `${props.projNameTitleCase}LogGroup`, {
            logGroupName: `/ecs/${props.projNameTitleCase}-${props.stage}`,
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            retention: props.logRetention || RetentionDays.ONE_WEEK
        });

        // Create tag definition custom resources
        this.createTagDefinitionCustomResources(props.tagDefinitions, props.stage, props.pikaServiceProjNameKebabCase);

        // Deploy mock tags S3 assets in non-production environments
        // Note: Tag registration (both built-in and mock) should be done via upload-tag-defs tool

        //TODO: remove this once we are ready to remove the mock tags feature completely
        // if (props.stage !== 'prod' && props.stage !== 'production') {
        //     this.deployMockWebComponents(pikaS3Bucket);
        // }

        // Create the Fargate service
        this.service = new ecs_patterns.ApplicationLoadBalancedFargateService(this, `${props.projNameTitleCase}FargateService`, {
            cluster: this.cluster,
            cpu: props.cpu || 512,
            desiredCount: props.desiredCount || 1,
            protocol: ApplicationProtocol.HTTPS,
            sslPolicy: SslPolicy.RECOMMENDED_TLS,
            enableExecuteCommand: false,
            memoryLimitMiB: props.memoryLimitMiB || 2048,
            publicLoadBalancer: props.makeLoadBalancerPublic || false,
            taskImageOptions: {
                containerName: `${props.projNameTitleCase}Task-${props.stage}`,
                image: ecs.ContainerImage.fromDockerImageAsset(this.dockerImage),
                containerPort: props.containerPort || 3000,
                environment: environmentVariables,
                taskRole: this.taskRole,
                enableLogging: true,
                logDriver: ecs.LogDriver.awsLogs({
                    streamPrefix: `${props.projNameTitleCase}-${props.stage}`,
                    logGroup: logGroup
                })
            },
            enableECSManagedTags: true,
            ...(props.certificate
                ? { certificate: props.certificate }
                : props.certificateArn
                  ? {
                        certificate: Certificate.fromCertificateArn(this, `${props.projNameTitleCase}Certificate-${props.stage}`, props.certificateArn)
                    }
                  : {}),
            ...(props.domainName ? { domainName: props.domainName } : {}),
            ...(props.hostedZoneId && props.domainName
                ? {
                      domainZone: HostedZone.fromHostedZoneAttributes(this, `${props.projNameTitleCase}DomainZone-${props.stage}`, {
                          hostedZoneId: props.hostedZoneId,
                          zoneName: props.domainName
                      })
                  }
                : {}),
            redirectHTTP: true,
            loadBalancerName: `${props.projNameTitleCase}LoadBalancer-${props.stage}`,
            minHealthyPercent: 50
        });

        // Ensure ECS service depends on key initialization custom resource
        this.service.node.addDependency(keyInitializerCustomResource);

        // Apply component tags to the Fargate service
        this.applyComponentTags(this.service, 'FargateService');
        this.applyComponentTags(this.taskRole, 'ECSTaskRole');

        // Configure health check
        this.service.targetGroup.configureHealthCheck({
            path: props.healthCheckPath || '/health',
            port: 'traffic-port',
            unhealthyThresholdCount: 5,
            timeout: cdk.Duration.seconds(60),
            interval: cdk.Duration.seconds(90)
        });

        // Set ALB idle timeout to match Lambda converse function timeout (300s).
        // AWS default is 60s, which causes ALB to drop streaming connections during
        // long-running agent responses (thinking phase, sequential tool calls).
        this.service.loadBalancer.setAttribute('idle_timeout.timeout_seconds', '300');

        if (props.domainName) {
            // Output the service URL
            new cdk.CfnOutput(this, 'ChatWebappUrl', {
                value: cdk.Fn.sub('${Value}', {
                    Value: `https://${props.domainName}`
                }).toString(),
                description: `${props.projNameHuman} Service URL`,
                exportName: `chat-webapp-url-${props.projNameKebabCase}-${props.stage}l`
            });
        }

        // Output the load balancer DNS name
        new cdk.CfnOutput(this, `${props.projNameTitleCase}LoadBalancerDns`, {
            value: this.service.loadBalancer.loadBalancerDnsName,
            description: `${props.projNameHuman} Load Balancer DNS Name`
        });
    }

    private createTagDefinitionCustomResources(tagDefinitions: TagDefinitionsJsonFile, stage: string, pikaServiceProjNameKebabCase: string): void {
        // Get the tag definition custom resource lambda ARN from SSM parameter
        const tagDefinitionCustomResourceArn = ssm.StringParameter.valueFromLookup(
            this,
            `/stack/${pikaServiceProjNameKebabCase}/${stage}/lambda/tag_definition_custom_resource_arn`
        );

        // Create a custom resource for each tag definition
        tagDefinitions.tagDefs.forEach((tagDef, index) => {
            new cdk.CustomResource(this, `TagDefinitionCustomResource-${tagDef.scope}-${tagDef.tag}`, {
                serviceToken: tagDefinitionCustomResourceArn,
                properties: {
                    TagDefData: tagDef.gzippedBase64EncodedString,
                    Stage: stage,

                    // This ensures that we always call the custom resource lambda
                    timestamp: Date.now().toString()
                }
            });
        });

        console.log(`Created ${tagDefinitions.tagDefs.length} tag definition custom resources`);
    }

    private deployMockWebComponents(pikaBucketName: string): void {
        console.log('Deploying mock web components for non-production environment...');

        // Get the Pika S3 bucket reference
        const pikaBucket = s3.Bucket.fromBucketName(this, 'PikaS3Bucket', pikaBucketName);

        // Path to mock tags directory (relative to this file)
        const mockTagsPath = path.resolve(__dirname, '../../../src/lib/mock-tags');
        const webComponentsPath = path.join(mockTagsPath, 'webcomponents');

        // Deploy hello-world.js to S3
        // We need to create a temporary gzipped version for CDK deployment
        const tempDir = path.join(__dirname, '../../../.temp-mock-tags');
        const fs = require('fs');

        // Create temp directory if it doesn't exist
        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir, { recursive: true });
        }

        // Gzip hello-world.js (stored as .js.txt to avoid TypeScript checking)
        const helloWorldPath = path.join(webComponentsPath, 'hello-world.js.txt');
        if (fs.existsSync(helloWorldPath)) {
            const content = readFileSync(helloWorldPath, 'utf-8');
            const gzipped = gzipSync(content);
            const gzippedPath = path.join(tempDir, 'hello-world.js.gz');
            fs.writeFileSync(gzippedPath, gzipped);

            // Deploy to S3
            new s3deploy.BucketDeployment(this, 'MockWebComponentsDeployment', {
                sources: [s3deploy.Source.asset(tempDir)],
                destinationBucket: pikaBucket,
                destinationKeyPrefix: 'wc/pika/',
                prune: false
            });

            console.log('Mock web components uploaded to S3');
            console.log('Note: Run "pnpm run upload-tag-defs" to register all tag definitions manually (built-in + mock)');
        } else {
            console.log('hello-world.js not found at:', helloWorldPath);
        }
    }

    /**
     * Creates component tags based on the configured component tag names.
     * Returns an object with tag key-value pairs for all configured component tag names.
     * If no component tag names are configured, returns an empty object.
     *
     * @param componentValue The value to use for the component tag (e.g., 'ECSCluster', 'KeyRotationLambda')
     * @returns Object with component tags, or empty object if no tag names configured
     *
     * @example
     * // If componentTagNames = ['component', 'resource-type']
     * // Returns: { component: 'ECSCluster', 'resource-type': 'ECSCluster' }
     * const tags = this.createComponentTags('ECSCluster');
     */
    private createComponentTags(componentValue: string): Record<string, string> {
        if (!this.props.componentTagNames || this.props.componentTagNames.length === 0) {
            return {};
        }

        const tags: Record<string, string> = {};
        for (const tagName of this.props.componentTagNames) {
            tags[tagName] = componentValue;
        }
        return tags;
    }

    /**
     * Applies component tags to a CDK construct.
     * This is a convenience method to apply component tags to any CDK resource.
     * Use this method to ensure consistent tagging across all infrastructure.
     *
     * @param construct The CDK construct to tag
     * @param componentValue The value to use for the component tag
     *
     * @example
     * const lambda = new lambda.Function(this, 'MyLambda', { ... });
     * this.applyComponentTags(lambda, 'MyLambda');
     */
    public applyComponentTags(construct: Construct, componentValue: string): void {
        const tags = this.createComponentTags(componentValue);
        for (const [key, value] of Object.entries(tags)) {
            cdk.Tags.of(construct).add(key, value);
        }
    }

    /**
     * Validates that tag environment variables don't exceed size limits.
     * AWS Lambda has a 4KB total limit for environment variables.
     * We conservatively limit tags to 500 bytes to leave room for other env vars.
     * 
     * @param envVars - The environment variables to validate
     * @throws Error if tag environment variables exceed the size limit
     */
    private validateTagEnvironmentVariableSize(envVars: Record<string, string>): void {
        const MAX_TAG_ENV_SIZE = 500; // Conservative limit to leave room for other env vars
        
        let totalSize = 0;
        if (envVars.STACK_TAGS) {
            totalSize += envVars.STACK_TAGS.length;
        }
        if (envVars.COMPONENT_TAG_NAMES) {
            totalSize += envVars.COMPONENT_TAG_NAMES.length;
        }

        if (totalSize > MAX_TAG_ENV_SIZE) {
            throw new Error(
                `Tag environment variables exceed size limit. ` +
                `Total size: ${totalSize} bytes, maximum: ${MAX_TAG_ENV_SIZE} bytes. ` +
                `STACK_TAGS size: ${envVars.STACK_TAGS?.length || 0} bytes, ` +
                `COMPONENT_TAG_NAMES size: ${envVars.COMPONENT_TAG_NAMES?.length || 0} bytes. ` +
                `Please reduce the number or length of tags in your pika-config.ts stackTags configuration.`
            );
        }
    }

    /**
     * Get environment variables for passing tags to Lambda custom resource functions and containers.
     * Returns STACK_TAGS and COMPONENT_TAG_NAMES as JSON strings that can be parsed.
     * 
     * Use this to pass tagging configuration so they can tag the AWS resources they create (e.g., KMS keys, etc.).
     *
     * @returns Environment variables object to spread into Lambda or container environment config
     * @throws Error if tag environment variables exceed size limits
     *
     * @example
     * const lambda = new nodejs.NodejsFunction(this, 'MyCustomResource', {
     *     environment: {
     *         ...this.getTagEnvironmentVariables(),
     *         OTHER_VAR: 'value'
     *     }
     * });
     */
    private getTagEnvironmentVariables(): Record<string, string> {
        const envVars: Record<string, string> = {};

        // Add stack tags if configured (from pika-config.ts)
        if (this.props.stackTags && Object.keys(this.props.stackTags).length > 0) {
            envVars.STACK_TAGS = JSON.stringify(this.props.stackTags);
        }

        // Add component tag names if configured (from pika-config.ts)
        if (this.props.componentTagNames && this.props.componentTagNames.length > 0) {
            envVars.COMPONENT_TAG_NAMES = JSON.stringify(this.props.componentTagNames);
        }

        // Validate size limits
        this.validateTagEnvironmentVariableSize(envVars);

        return envVars;
    }
}
