import * as cdk from 'aws-cdk-lib';
import { Certificate, ICertificate } from 'aws-cdk-lib/aws-certificatemanager';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecr_assets from 'aws-cdk-lib/aws-ecr-assets';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecs_patterns from 'aws-cdk-lib/aws-ecs-patterns';
import { ApplicationProtocol, SslPolicy } from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as nodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import { LogGroup, RetentionDays } from 'aws-cdk-lib/aws-logs';
import { HostedZone } from 'aws-cdk-lib/aws-route53';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import { Construct } from 'constructs';
import { TagDefinitionsJsonFile } from 'pika-shared/types/chatbot/chatbot-types.js';
import { generateKmsKeyAliasName } from '../../../src/lib/server/encryption/kms-utils';

const COOKIE_MAX_AGE_HOURS = 12;
const KEY_ROTATION_INTERVAL_HOURS = 12;
const KEY_REFRESH_INTERVAL_HOURS = 1;
const MAX_KEY_VERSIONS = '3';

export interface PikaChatConstructProps {
    /**
     * The stage/environment name (e.g., 'dev', 'staging', 'prod')
     */
    stage: string;

    /**
     * VPC to deploy the service into
     */
    vpc: ec2.IVpc;

    /**
     * Certificate ARN for HTTPS, if provided will use Certificate.fromCertificateArn to create the certificate.
     * Use this or certificate, not both. You must provide one or the other.
     */
    certificateArn?: string;

    /**
     * Certificate for HTTPS, if provided will use as is in ecs task definition.
     * Use this or certificateArn, not both. You must provide one or the other.
     */
    certificate?: ICertificate;

    /**
     * Domain name for the pika chat webapp (e.g., 'chat.example.com' or 'test-chat.example.com'). Must be fully qualified domain name.
     */
    domainName?: string;

    /**
     * Hosted Zone ID for Route53 (optional).  If provided, domainName must also be provided and the domain must be in this hosted zone.
     */
    hostedZoneId?: string;

    /**
     * Path to the directory containing the Dockerfile (relative to this construct file)
     */
    dockerBuildPath: string;

    /**
     * Additional environment variables to add to the ECS task
     */
    additionalEnvironmentVariables?: Record<string, string>;

    /**
     * Whether to make the load balancer public (default: false)
     */
    makeLoadBalancerPublic?: boolean;

    /**
     * CPU units for the Fargate task (default: 512)
     */
    cpu?: number;

    /**
     * Memory limit in MiB for the Fargate task (default: 2048)
     */
    memoryLimitMiB?: number;

    /**
     * Desired count of running tasks (default: 1)
     */
    desiredCount?: number;

    /**
     * Container port (default: 3000)
     */
    containerPort?: number;

    /**
     * Health check path (default: '/health')
     */
    healthCheckPath?: string;

    /**
     * Log retention period (default: ONE_WEEK)
     */
    logRetention?: RetentionDays;

    /**
     * Project name in all lowercase e.g. pikachat
     */
    projNameL: string;

    /**
     * Project name in title case e.g. PikaChat
     */
    projNameTitleCase: string;

    /**
     * Project name in camel case e.g. pikaChat
     */
    projNameCamel: string;

    /**
     * Project name in kebab case e.g. pika-chat
     */
    projNameKebabCase: string;

    /**
     * Project name in human readable e.g. Pika Chat
     */
    projNameHuman: string;

    /**
     * Project name in kebab case for the pika service stack e.g. pika
     */
    pikaServiceProjNameKebabCase: string;

    /**
     * Tag definitions for the pika chat stack.  This is generated by the generate-tag-defs-for-build tool.
     */
    tagDefinitions: TagDefinitionsJsonFile;
}

/** Includes the things we know have to be provided by whomever implements the getPikaChatConstructProps function. */
export type PartialPikaChatConstructProps = Omit<PikaChatConstructProps, 'vpc'>;

export class PikaChatConstruct extends Construct {
    public readonly service: ecs_patterns.ApplicationLoadBalancedFargateService;
    public readonly cluster: ecs.Cluster;
    public readonly dockerImage: ecr_assets.DockerImageAsset;
    public readonly taskRole: iam.Role;

    constructor(scope: Construct, id: string, props: PikaChatConstructProps) {
        super(scope, id);

        //BXTODO
        // Build the full domain name

        // Create Docker image asset
        this.dockerImage = new ecr_assets.DockerImageAsset(this, `${props.projNameTitleCase}Image`, {
            directory: props.dockerBuildPath,
            buildArgs: {
                BUILDPLATFORM: 'linux/amd64'
            },
            platform: ecr_assets.Platform.LINUX_AMD64
        });

        // Store the image URI in SSM for reference by other services
        new ssm.StringParameter(this, `${props.projNameTitleCase}EcrImageUriParam`, {
            parameterName: `/stack/${props.projNameKebabCase}/${props.stage}/ecr/${props.projNameKebabCase}-image-uri`,
            stringValue: this.dockerImage.imageUri,
            description: `URI of the ${props.projNameHuman} Docker image in ECR`
        });

        // Create ECS cluster
        this.cluster = new ecs.Cluster(this, `${props.projNameTitleCase}Cluster`, {
            vpc: props.vpc
        });

        // Param comes from the pika service stack
        const apiId = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/api/id`);

        // Param comes from the pika service stack
        const chatAdminApiId = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/api/chat_admin_id`);

        // Param comes from the pika service stack
        const converseFnUrl = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/function/converse_url`);

        // Param comes from the pika service stack
        const chatAppTableArn = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/ddb_table/chat_app_table_arn`);

        // Param comes from the pika service stack
        const pikaS3Bucket = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/s3/pika_bucket_name`);

        // Param comes from the pika service stack
        const pikaS3BucketArn = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/s3/pika_bucket_arn`);

        // Param comes from the pika service stack
        const tagDefinitionsTableArn = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/ddb_table/pika_tag_def_arn`);

        // Param comes from the pika service stack
        const tagDefinitionsTableName = ssm.StringParameter.valueForStringParameter(this, `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/ddb_table/pika_tag_def`);

        // ===== COOKIE ENCRYPTION INFRASTRUCTURE =====

        // IAM role for key rotation Lambda
        const rotationFunctionRole = new iam.Role(this, `${props.projNameTitleCase}KeyRotationRole`, {
            assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
            managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
            inlinePolicies: {
                KeyRotationPolicy: new iam.PolicyDocument({
                    statements: [
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['ssm:GetParameter', 'ssm:GetParameters', 'ssm:GetParametersByPath', 'ssm:PutParameter', 'ssm:DeleteParameter'],
                            resources: [
                                `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption`,
                                `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption/*`
                            ]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:GenerateDataKey', 'kms:Decrypt'],
                            resources: ['*'],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/Project': props.projNameKebabCase,
                                    'aws:ResourceTag/Stage': props.stage,
                                    'aws:ResourceTag/Purpose': 'CookieEncryption'
                                }
                            }
                        })
                    ]
                })
            }
        });

        // Lambda function for key rotation (scheduled and invoked by initializer)
        const rotationFunction = new nodejs.NodejsFunction(this, `${props.projNameTitleCase}KeyRotationFunction`, {
            functionName: `${props.projNameTitleCase}KeyRotationFunction-${props.stage}`,
            runtime: lambda.Runtime.NODEJS_22_X,
            entry: 'infra/lambda/cookie-key-rotation/index.ts',
            handler: 'handler',
            timeout: cdk.Duration.seconds(60),
            memorySize: 256,
            environment: {
                NODE_OPTIONS: '--enable-source-maps',
                STAGE: props.stage,
                SSM_PARAMETER_PREFIX: `/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption`,
                KMS_KEY_ALIAS: generateKmsKeyAliasName(props.projNameKebabCase, props.stage),
                MAX_KEY_VERSIONS: MAX_KEY_VERSIONS
            },
            role: rotationFunctionRole,
            bundling: {
                minify: true,
                sourceMap: true,
                target: 'node22',
                externalModules: ['@aws-sdk']
            }
        });

        // IAM role for KMS key initializer Lambda (Custom Resource)
        // This Lambda only creates KMS keys and SSM key alias parameters
        const keyInitializerFunctionRole = new iam.Role(this, `${props.projNameTitleCase}KeyInitializerRole`, {
            assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
            managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
            inlinePolicies: {
                KeyInitializerPolicy: new iam.PolicyDocument({
                    statements: [
                        // SSM permissions for storing key alias
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['ssm:PutParameter', 'ssm:DeleteParameter', 'ssm:GetParameter', 'ssm:GetParametersByPath'],
                            resources: [`arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/kms/*`]
                        }),
                        // SSM permissions for cookie encryption parameters (needed for rotateKeys call)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['ssm:GetParameter', 'ssm:GetParameters', 'ssm:GetParametersByPath', 'ssm:PutParameter', 'ssm:DeleteParameter'],
                            resources: [
                                // Parent path permission (required for GetParametersByPath)
                                `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption`,
                                // Child parameters permission
                                `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption/*`
                            ]
                        }),
                        // KMS CreateKey with key specification conditions
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:CreateKey'],
                            resources: ['*'],
                            conditions: {
                                StringEquals: {
                                    'kms:KeySpec': 'SYMMETRIC_DEFAULT',
                                    'kms:KeyUsage': 'ENCRYPT_DECRYPT'
                                }
                            }
                        }),
                        // KMS key policy management (unrestricted for key creation)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:PutKeyPolicy', 'kms:GetKeyPolicy'],
                            resources: [`arn:aws:kms:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:key/*`]
                        }),
                        // KMS alias operations (unrestricted for key infrastructure setup)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:CreateAlias', 'kms:DeleteAlias'],
                            resources: [`arn:aws:kms:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:alias/*`]
                        }),

                        // KMS key operations - restricted to keys with specific tags
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: [
                                'kms:DescribeKey',
                                'kms:ScheduleKeyDeletion',
                                'kms:CancelKeyDeletion', // In case deletion needs to be cancelled
                                'kms:EnableKey', // In case key gets disabled
                                'kms:TagResource',
                                'kms:CreateAlias', // Needed on key resource when creating alias
                                'kms:DeleteAlias' // Needed on key resource when deleting alias
                            ],
                            resources: [`arn:aws:kms:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:key/*`],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/Project': props.projNameKebabCase,
                                    'aws:ResourceTag/Stage': props.stage,
                                    'aws:ResourceTag/Purpose': 'CookieEncryption'
                                }
                            }
                        }),

                        // KMS ListAliases (requires * and no conditions work reliably)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:ListAliases'],
                            resources: ['*']
                        }),
                        // KMS data key operations for key rotation (needed for rotateKeys call)
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:GenerateDataKey', 'kms:Decrypt'],
                            resources: ['*'],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/Project': props.projNameKebabCase,
                                    'aws:ResourceTag/Stage': props.stage,
                                    'aws:ResourceTag/Purpose': 'CookieEncryption'
                                }
                            }
                        }),
                        // STS permissions for getting account ID
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['sts:GetCallerIdentity'],
                            resources: ['*']
                        })
                    ]
                })
            }
        });

        // Lambda function for KMS key initialization (Custom Resource)
        // This only creates KMS keys, not the encryption key rotation
        const keyInitializerFunction = new nodejs.NodejsFunction(this, `${props.projNameTitleCase}KeyInitializerFunction`, {
            runtime: lambda.Runtime.NODEJS_22_X,
            entry: 'infra/lambda/cookie-key-initializer/index.ts',
            handler: 'handler',
            timeout: cdk.Duration.seconds(300), // Increased timeout for KMS operations
            memorySize: 512, // Increased memory for AWS SDK operations
            environment: {
                NODE_OPTIONS: '--enable-source-maps',
                STAGE: props.stage,
                SSM_PARAMETER_PREFIX: `/stack/${props.projNameKebabCase}/${props.stage}/cookie-encryption`,
                KMS_KEY_ALIAS: generateKmsKeyAliasName(props.projNameKebabCase, props.stage),
                MAX_KEY_VERSIONS: MAX_KEY_VERSIONS
            },
            role: keyInitializerFunctionRole,
            bundling: {
                minify: true,
                sourceMap: true,
                target: 'node22',
                externalModules: ['@aws-sdk']
            }
        });

        // EventBridge rule for scheduled rotation (every 12 hours)
        new events.Rule(this, `${props.projNameTitleCase}KeyRotationRule`, {
            schedule: events.Schedule.rate(cdk.Duration.hours(KEY_ROTATION_INTERVAL_HOURS)),
            targets: [
                new targets.LambdaFunction(rotationFunction, {
                    event: events.RuleTargetInput.fromObject({
                        // Using environment variables for scheduled invocations
                        // forceRotation is not set, so it will check if rotation is needed
                    })
                })
            ]
        });

        // Custom resource for KMS key initialization
        // This will create KMS keys and invoke rotation function for initial key setup
        const keyInitializerCustomResource = new cdk.CustomResource(this, `${props.projNameTitleCase}KeyInitializerCustomResource`, {
            serviceToken: keyInitializerFunction.functionArn,
            properties: {
                // Add timestamp to ensure custom resource runs on every deployment
                Timestamp: Date.now().toString(),
                Stage: props.stage,
                ProjectName: props.projNameKebabCase
            }
        });

        // Create task role with necessary permissions
        this.taskRole = new iam.Role(this, `${props.projNameTitleCase}TaskRole`, {
            assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
            inlinePolicies: {
                ExecuteApiPolicy: new iam.PolicyDocument({
                    statements: [
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['execute-api:Invoke'],
                            resources: [
                                `arn:aws:execute-api:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:${apiId}/*`,
                                `arn:aws:execute-api:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:${chatAdminApiId}/*`
                            ]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['execute-api:Invoke'],
                            resources: [`arn:aws:execute-api:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:*/*`],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/pika-api': 'true'
                                }
                            }
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['ssm:GetParameter', 'ssm:GetParameters', 'ssm:GetParametersByPath'],
                            resources: [`arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter/*`]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['kms:Decrypt'], // Webapp only needs to decrypt existing keys
                            resources: ['*'],
                            conditions: {
                                StringEquals: {
                                    'aws:ResourceTag/Project': props.projNameKebabCase,
                                    'aws:ResourceTag/Stage': props.stage,
                                    'aws:ResourceTag/Purpose': 'CookieEncryption'
                                }
                            }
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['lambda:InvokeFunctionUrl', 'lambda:InvokeFunction'],
                            resources: [
                                ssm.StringParameter.valueForStringParameter(
                                    this,
                                    `/stack/${props.pikaServiceProjNameKebabCase}/${props.stage}/function/converse_arn` // Comes from the pika service stack
                                )
                            ]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['sts:GetCallerIdentity'],
                            resources: ['*']
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['dynamodb:GetItem', 'dynamodb:Query', 'dynamodb:Scan', 'dynamodb:BatchGetItem'],
                            resources: [chatAppTableArn]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: ['s3:GetObject', 's3:PutObject', 's3:DeleteObject', 's3:GetObjectAcl', 's3:PutObjectAcl', 's3:PutObjectTagging'],
                            resources: [pikaS3BucketArn, `${pikaS3BucketArn}/*`]
                        }),
                        new iam.PolicyStatement({
                            effect: iam.Effect.ALLOW,
                            actions: [
                                'dynamodb:GetItem',
                                'dynamodb:PutItem',
                                'dynamodb:UpdateItem',
                                'dynamodb:DeleteItem',
                                'dynamodb:Query',
                                'dynamodb:Scan',
                                'dynamodb:BatchGetItem',
                                'dynamodb:BatchWriteItem'
                            ],
                            resources: [tagDefinitionsTableArn, `${tagDefinitionsTableArn}/*`]
                        })
                    ]
                })
            }
        });

        // Build environment variables
        const baseEnvironmentVariables = {
            STAGE: props.stage,
            ENV: props.stage,
            AWS_REGION: cdk.Aws.REGION,
            AWS_ACCOUNT_ID: cdk.Aws.ACCOUNT_ID,
            CHAT_API_ID: apiId,
            CHAT_ADMIN_API_ID: chatAdminApiId,
            WEBAPP_URL: props.domainName
                ? cdk.Fn.sub('${Value}', {
                      Value: `https://${props.domainName}`
                  }).toString()
                : 'unknown',
            PIKA_S3_BUCKET: pikaS3Bucket,
            CONVERSE_FUNCTION_URL: converseFnUrl,
            TAG_DEFINITIONS_TABLE: tagDefinitionsTableName,
            PIKA_SERVICE_PROJ_NAME_KEBAB_CASE: props.pikaServiceProjNameKebabCase,
            PIKA_CHAT_PROJ_NAME_KEBAB_CASE: props.projNameKebabCase,
            // Cookie key rotation configuration - will be created by infrastructure manager
            KMS_COOKIE_KEY_ALIAS: generateKmsKeyAliasName(props.projNameKebabCase, props.stage),
            KEY_REFRESH_INTERVAL_HOURS: String(KEY_REFRESH_INTERVAL_HOURS),
            MAX_KEY_VERSIONS: String(MAX_KEY_VERSIONS),
            COOKIE_MAX_AGE_HOURS: String(COOKIE_MAX_AGE_HOURS)
        };

        const environmentVariables = {
            ...baseEnvironmentVariables,
            ...props.additionalEnvironmentVariables
        };

        // Create log group first to preserve logical ID
        const logGroup = new LogGroup(this, `${props.projNameTitleCase}LogGroup`, {
            logGroupName: `/ecs/${props.projNameTitleCase}-${props.stage}`,
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            retention: props.logRetention || RetentionDays.ONE_WEEK
        });

        // Create tag definition custom resources
        this.createTagDefinitionCustomResources(props.tagDefinitions, props.stage, props.pikaServiceProjNameKebabCase);

        // Create the Fargate service
        this.service = new ecs_patterns.ApplicationLoadBalancedFargateService(this, `${props.projNameTitleCase}FargateService`, {
            cluster: this.cluster,
            cpu: props.cpu || 512,
            desiredCount: props.desiredCount || 1,
            protocol: ApplicationProtocol.HTTPS,
            sslPolicy: SslPolicy.RECOMMENDED_TLS,
            enableExecuteCommand: false,
            memoryLimitMiB: props.memoryLimitMiB || 2048,
            publicLoadBalancer: props.makeLoadBalancerPublic || false,
            taskImageOptions: {
                containerName: `${props.projNameTitleCase}Task-${props.stage}`,
                image: ecs.ContainerImage.fromDockerImageAsset(this.dockerImage),
                containerPort: props.containerPort || 3000,
                environment: environmentVariables,
                taskRole: this.taskRole,
                enableLogging: true,
                logDriver: ecs.LogDriver.awsLogs({
                    streamPrefix: `${props.projNameTitleCase}-${props.stage}`,
                    logGroup: logGroup
                })
            },
            enableECSManagedTags: true,
            ...(props.certificate
                ? { certificate: props.certificate }
                : props.certificateArn
                  ? {
                        certificate: Certificate.fromCertificateArn(this, `${props.projNameTitleCase}Certificate-${props.stage}`, props.certificateArn)
                    }
                  : {}),
            ...(props.domainName ? { domainName: props.domainName } : {}),
            ...(props.hostedZoneId && props.domainName
                ? {
                      domainZone: HostedZone.fromHostedZoneAttributes(this, `${props.projNameTitleCase}DomainZone-${props.stage}`, {
                          hostedZoneId: props.hostedZoneId,
                          zoneName: props.domainName
                      })
                  }
                : {}),
            redirectHTTP: true,
            loadBalancerName: `${props.projNameTitleCase}LoadBalancer-${props.stage}`,
            minHealthyPercent: 50
        });

        // Ensure ECS service depends on key initialization custom resource
        this.service.node.addDependency(keyInitializerCustomResource);

        // Configure health check
        this.service.targetGroup.configureHealthCheck({
            path: props.healthCheckPath || '/health',
            port: 'traffic-port',
            unhealthyThresholdCount: 5,
            timeout: cdk.Duration.seconds(60),
            interval: cdk.Duration.seconds(90)
        });

        if (props.domainName) {
            // Output the service URL
            new cdk.CfnOutput(this, 'ChatWebappUrl', {
                value: cdk.Fn.sub('${Value}', {
                    Value: `https://${props.domainName}`
                }).toString(),
                description: `${props.projNameHuman} Service URL`,
                exportName: `chat-webapp-url-${props.projNameKebabCase}-${props.stage}l`
            });
        }

        // Output the load balancer DNS name
        new cdk.CfnOutput(this, `${props.projNameTitleCase}LoadBalancerDns`, {
            value: this.service.loadBalancer.loadBalancerDnsName,
            description: `${props.projNameHuman} Load Balancer DNS Name`
        });
    }

    private createTagDefinitionCustomResources(tagDefinitions: TagDefinitionsJsonFile, stage: string, pikaServiceProjNameKebabCase: string): void {
        // Get the tag definition custom resource lambda ARN from SSM parameter
        const tagDefinitionCustomResourceArn = ssm.StringParameter.valueFromLookup(
            this,
            `/stack/${pikaServiceProjNameKebabCase}/${stage}/lambda/tag_definition_custom_resource_arn`
        );

        // Create a custom resource for each tag definition
        tagDefinitions.tagDefs.forEach((tagDef, index) => {
            new cdk.CustomResource(this, `TagDefinitionCustomResource-${tagDef.scope}-${tagDef.tag}`, {
                serviceToken: tagDefinitionCustomResourceArn,
                properties: {
                    TagDefData: tagDef.gzippedBase64EncodedString,
                    Stage: stage,

                    // This ensures that we always call the custom resource lambda
                    timestamp: Date.now().toString()
                }
            });
        });

        console.log(`Created ${tagDefinitions.tagDefs.length} tag definition custom resources`);
    }
}
