/**
 * Do not include any other imports in this file.  It is typescript only to give you the type of the tag definition.
 * Think of it is a json object.  You must return  `TagDefinitionForCreateOrUpdate<TagDefinitionWidgetPikaCompiledIn>`
 * as the default export.
 */
import type { TagDefinitionForCreateOrUpdate, TagDefinitionWidgetPikaCompiledIn } from 'pika-shared/types/chatbot/chatbot-types';

const tagDefinition: TagDefinitionForCreateOrUpdate<TagDefinitionWidgetPikaCompiledIn> = {
    tag: 'chart',
    legacyTagName: 'chart',
    scope: 'pika',
    tagTitle: 'Charts',
    description: 'A chart is a visual representation of data.  It will be generated by the LLM.',
    canBeGeneratedByLlm: true,
    canBeGeneratedByTool: true,
    status: 'enabled',
    chatAppId: 'chat-app-global',
    renderingContexts: {
        inline: { enabled: true },
        canvas: { enabled: true },
        dialog: { enabled: true }
    },
    shortTagEx: '<pika.chart></pika.chart>',
    widget: {
        type: 'pika-compiled-in'
    },
    llmInstructionsMd: `  - To include a chart, use the \`<pika.chart></pika.chart>\` tags.
  - The content within the tags MUST be valid Chart.js version 4 JSON, including \`type\` and \`data\` properties.
  - **Example:** \`<pika.chart>{"type":"line","data":{"labels":["May","June","July","August"],"datasets":[{"label":"Avg Temperature (°C)","data":[2,3,7,12]}]}}</pika.chart>\`
  - **Usage:** Include pika charts whenever they can visually represent data, trends, or comparisons effectively.
  - **Presentation**
    - **Timeframes**: For any data or insights provided over a period, you MUST explicitly state the timeframe or time range of the data.
    - **Timezones**: IMPORTANT: Display time in users timezone when possible.`
};

export default tagDefinition;
