/**
 * Do not include any other imports in this file.  It is typescript only to give you the type of the tag definition.
 * Think of it is a json object.  You must return  `TagDefinitionForCreateOrUpdate<TagDefinitionWidgetPikaCompiledIn>`
 * as the default export.
 */
import type { TagDefinitionForCreateOrUpdate, TagDefinitionWidgetPikaCompiledIn } from 'pika-shared/types/chatbot/chatbot-types';

const tagDefinition: TagDefinitionForCreateOrUpdate<TagDefinitionWidgetPikaCompiledIn> = {
    tag: 'chart',
    legacyTagName: 'chart',
    scope: 'pika',
    tagTitle: 'Charts',
    description: 'A chart is a visual representation of data.  It will be generated by the LLM.',
    canBeGeneratedByLlm: true,
    canBeGeneratedByTool: true,
    shortTagEx: '<chart></chart>',
    widget: {
        type: 'pika-compiled-in'
    },
    llmInstructions: [
        {
            type: 'line',
            mdLine: 'To include a chart, use the `<pika.chart></pika.chart>` tags.'
        },
        {
            type: 'line',
            mdLine: 'The content within the tags MUST be valid Chart.js version 4 JSON, including `type` and `data` properties.'
        },
        {
            type: 'line',
            mdLine: 'Use this tag when the focus of the response is a chart.'
        },
        {
            type: 'line',
            title: 'Example',
            mdLine: '<pika.chart>{"type":"line","data":{"labels":["May","June","July","August"],"datasets":[{"label":"Avg Temperature (°C)","data":[2,3,7,12],"backgroundColor":"rgba(255,159,64,0.2)","borderColor":"rgba(255,159,64,1)","borderWidth": 1}]}}</pika.chart>'
        },
        {
            type: 'line',
            title: 'Usage',
            mdLine: 'Include charts whenever they can visually represent data, trends, or comparisons effectively. This greatly enhances user experience.'
        },
        {
            type: 'block',
            title: 'Presentation',
            lines: [
                {
                    type: 'line',
                    title: 'Timeframes',
                    mdLine: 'For any data or insights provided over a period, you MUST explicitly state the timeframe or time range of the data.'
                },
                {
                    type: 'line',
                    title: 'Timezones',
                    mdLine: 'IMPORTANT: Display time in users timezone when possible.'
                }
            ]
        }
    ]
};

export default tagDefinition;
