import path from 'path';
import { fileURLToPath } from 'url';
import { readFileSync, writeFileSync } from 'fs';
import { serialize } from 'seroval';
import { format } from 'prettier';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
    const destPath = path.join(__dirname, '../../../../services/pika/src/lib/custom-site-features.ts');
    const pikaConfigPath = path.join(__dirname, '../../../../pika-config.ts');
    let fileContents = readFileSync(pikaConfigPath, 'utf8');

    // Extract the siteFeatures object from the pikaConfig - using brittle string manipulation
    const siteFeaturesStart = fileContents.indexOf('siteFeatures: {');

    let siteFeatures;
    if (siteFeaturesStart !== -1) {
        // Find the matching closing brace by counting braces
        let braceCount = 0;
        let startIndex = siteFeaturesStart + 'siteFeatures: '.length;
        let endIndex = startIndex;

        for (let i = startIndex; i < fileContents.length; i++) {
            if (fileContents[i] === '{') {
                braceCount++;
            } else if (fileContents[i] === '}') {
                braceCount--;
                if (braceCount === 0) {
                    endIndex = i + 1;
                    break;
                }
            }
        }

        const siteFeaturesContent = fileContents.substring(startIndex, endIndex);
        try {
            siteFeatures = eval(`(${siteFeaturesContent})`);
        } catch (e) {
            console.error('Failed to parse siteFeatures:', e);
            siteFeatures = undefined;
        }
    } else {
        siteFeatures = undefined;
    }

    const rawSerialized = siteFeatures ? serialize(siteFeatures) : 'undefined';

    // Replace minified boolean literals with readable ones
    const readableSerialized = rawSerialized.replace(/!0/g, 'true').replace(/!1/g, 'false');

    const unformattedContent = `/** Do not change this file.  It is generated by the copy-pika-config tool when you run locally or build. */

import type { SiteFeatures } from "pika-shared/types/chatbot/chatbot-types";

export const siteFeatures: SiteFeatures | undefined = ${readableSerialized};
`;

    // Format the content with Prettier
    const fileContent = await format(unformattedContent, {
        parser: 'typescript',
        tabWidth: 4,
        useTabs: false,
        singleQuote: true,
        trailingComma: 'es5',
        printWidth: 100
    });

    writeFileSync(destPath, fileContent);
}

(async () => {
    try {
        await main();
    } catch (error) {
        console.error(error);
        process.exit(1);
    }
})();
