/**
 * Session Generator - Creates actual test sessions in the database
 *
 * This module provides utilities to create real sessions in the database for testing
 * shared session and pinned session functionality. These sessions are marked as test
 * data and will be cleaned up by the bulk delete operations.
 */

import { createTestSession, ESSENTIAL_TEST_DATA, generateTestId } from './general-mocks';
import { externalAcmeUser1, externalAcmeUser2, externalStarkUser1, internalUserNoEntity } from './user-mock';
import type { ChatSessionForCreate } from './general-mocks';

/**
 * Create a test session for testing shared/pinned functionality
 */
export async function createTestSessionInDb(
    userId: string = externalAcmeUser1.userId,
    chatAppId: string = ESSENTIAL_TEST_DATA.CHAT_APP_ID,
    agentId: string = ESSENTIAL_TEST_DATA.AGENT_ID,
    entityId: string = 'acme-account'
): Promise<{ sessionId: string; sessionData: ChatSessionForCreate & { test: true } }> {
    const sessionId = generateTestId('session');
    const sessionData = createTestSession(userId, chatAppId, agentId, entityId, `Test Session for ${userId}`);

    // Note: sessionId will be generated by the database when the session is created
    // We return our desired sessionId for test reference, but the actual session
    // will get its ID from the database

    // TODO: Call the chat-admin API to actually create this session in the database
    // For now, we just return the session data - the actual API calls will be implemented
    // when we connect to the real database

    console.log(`📝 Generated test session: ${sessionId} for user: ${userId}`);

    return {
        sessionId,
        sessionData
    };
}

/**
 * Create multiple test sessions for comprehensive testing
 */
export async function createTestSessionBatch(): Promise<{
    acmeUserSession: { sessionId: string; sessionData: ChatSessionForCreate & { test: true } };
    acmeUser2Session: { sessionId: string; sessionData: ChatSessionForCreate & { test: true } };
    starkUserSession: { sessionId: string; sessionData: ChatSessionForCreate & { test: true } };
    internalUserSession: { sessionId: string; sessionData: ChatSessionForCreate & { test: true } };
}> {
    console.log('📦 Creating batch of test sessions...');

    const [acmeUserSession, acmeUser2Session, starkUserSession, internalUserSession] = await Promise.all([
        createTestSessionInDb(externalAcmeUser1.userId, ESSENTIAL_TEST_DATA.CHAT_APP_ID, ESSENTIAL_TEST_DATA.AGENT_ID, 'acme-account'),
        createTestSessionInDb(externalAcmeUser2.userId, ESSENTIAL_TEST_DATA.CHAT_APP_ID, ESSENTIAL_TEST_DATA.AGENT_ID, 'acme-account'),
        createTestSessionInDb(externalStarkUser1.userId, ESSENTIAL_TEST_DATA.CHAT_APP_ID, ESSENTIAL_TEST_DATA.AGENT_ID, 'stark-account'),
        createTestSessionInDb(internalUserNoEntity.userId, ESSENTIAL_TEST_DATA.CHAT_APP_ID, ESSENTIAL_TEST_DATA.AGENT_ID, 'chat-app-global')
    ]);

    console.log('Test session batch created successfully');

    return {
        acmeUserSession,
        acmeUser2Session,
        starkUserSession,
        internalUserSession
    };
}

/**
 * Pre-defined test sessions for common scenarios
 */
export const TEST_SESSION_SCENARIOS = {
    ACME_USER_ENTITY_ENABLED: {
        userId: externalAcmeUser1.userId,
        chatAppId: ESSENTIAL_TEST_DATA.CHAT_APP_ID,
        agentId: ESSENTIAL_TEST_DATA.AGENT_ID,
        entityId: 'acme-account'
    },
    STARK_USER_ENTITY_ENABLED: {
        userId: externalStarkUser1.userId,
        chatAppId: ESSENTIAL_TEST_DATA.CHAT_APP_ID,
        agentId: ESSENTIAL_TEST_DATA.AGENT_ID,
        entityId: 'stark-account'
    },
    INTERNAL_USER_GLOBAL_ENTITY: {
        userId: internalUserNoEntity.userId,
        chatAppId: ESSENTIAL_TEST_DATA.CHAT_APP_ID,
        agentId: ESSENTIAL_TEST_DATA.AGENT_ID,
        entityId: 'chat-app-global'
    },
    ENTITY_DISABLED_CHAT_APP: {
        userId: externalAcmeUser1.userId,
        chatAppId: `${ESSENTIAL_TEST_DATA.CHAT_APP_ID}-no-entity`,
        agentId: ESSENTIAL_TEST_DATA.AGENT_ID,
        entityId: 'chat-app-global'
    }
} as const;

/**
 * Create session for a specific test scenario
 */
export async function createSessionForScenario(scenario: keyof typeof TEST_SESSION_SCENARIOS): Promise<{ sessionId: string; sessionData: ChatSessionForCreate & { test: true } }> {
    const config = TEST_SESSION_SCENARIOS[scenario];
    return await createTestSessionInDb(config.userId, config.chatAppId, config.agentId, config.entityId);
}
